---
- name: Test
  hosts: net01-rtr1
  gather_facts: false
  vars:
    bgp_config: |
      router bgp 64512
        router-id 172.16.0.1
        neighbor 10.0.0.2 remote-as 64513
        neighbor 10.0.0.2 description net01-rtr2
        network 192.168.1.0/24

  tasks:
    - name: Include SoT variables
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_fileglob:
        - topologies/net01/{{ inventory_hostname }}/config_vars/*
      register: results


    - name: Apply configuration from SoT
      arista.eos.eos_config:
        lines: "{{ bgp_config }}"
        match: strict
        replace: block
        parents: router bgp 64512
        save_when: modified
      register: config_output

    - arista.eos.eos_command:
        commands: show history