---
- name: Automatic network issues recovery
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: 192.168.122.110
        port: 9092
        topic: arista_events

  rules:
    - name: Interface recovery
      # condition: true
      # action:
      #   debug:
      #     msg: "Received event: {{ event }}"
      condition: event.body.fields.oper_status == "DOWN"
      action:
        debug:
          msg: "{{ event.body.name }}"
        # run_job_template:
        #   name: "Network EDA - interface recovery"
        #   job_args:
        #     extra_vars:
        #       interface: "{{ event.body.name }}"
