---
- name: Automatic network issues recovery
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: 192.168.122.110
        port: 9092
        topic: network-events

  rules:
    - name: Interface recovery
      condition: true
      action:
        debug: