---
- name: Automatic network issues recovery
  hosts: all
  sources:
    - kafka:
        host: 192.168.122.110
        port: 9092
        topic: arista_events

  rules:
    - name: Interface recovery
      condition: true
      action:
        debug:
          msg: "Received event: {{ event }}"
      # condition: event.fields.oper_status == "DOWN"
      # action:
        # run_job_template:
        #   name: "Network EDA - interface recovery"
        #   job_args:
        #     extra_vars:
        #       interface: "{{ event.name }}"
