---
- name: Automatic network issues recovery
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: 192.168.122.110
        port: 9092
        topic: network-events

  rules:
    - name: Interface recovery
      condition: event[0].values["/interfaces/interface/state/oper-status"] == "DOWN"
      action:
        run_job_template:
          name: "Network EDA - interface recovery"
          organization: Default
          job_args:
            extra_vars:
              interface: "{{ event.tags.interface_name }}"
              device: "{{ event.tags.source }}"

    # - name: Protect network configuration
    #   condition: event.body.fields.oper_status == "DOWN"
    #   action:
    #     run_job_template:
    #       name: "Network EDA - protect network configuration"
    #       organization: Default
    #       job_args:
    #         extra_vars:
    #           interface: "{{ event.body.tags.name }}"












    # - name: Interface recovery
    #   condition: event.body.fields.oper_status == "DOWN"
    #   action:
    #     run_job_template:
    #       name: "Network EDA - interface recovery"
    #       organization: Default
    #       job_args:
    #         extra_vars:
    #           interface: "{{ event.body.tags.name }}"

    # - name: Protect network configuration
    #   condition: event.body.fields.oper_status == "DOWN"
    #   action:
    #     run_job_template:
    #       name: "Network EDA - protect network configuration"
    #       organization: Default
    #       job_args:
    #         extra_vars:
    #           interface: "{{ event.body.tags.name }}"
