---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/de-supported-rhel8:latest

additional_build_steps:
  append_final:
    - ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.11/site-packages:/usr/local/lib64/python3.11/site-packages
