---
#Added packages from requirements.txt https://github.com/ansible/event-driven-ansible
version: 3

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/de-supported-rhel9:latest

dependencies:
  python:
    - pyyaml>=6.0.1
    - aiobotocore
    - aiohttp
    - aiokafka
    - azure-servicebus
    - dpath
    - kafka-python; python_version < "3.12"
    - kafka-python-ng;  python_version >= "3.12"
    - systemd-python; sys_platform != 'darwin'
    - watchdog>=5.0.0
    - xxhash

  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner