---
- name: Configure network devices from SoT
  hosts: net01
  gather_facts: false
  vars: 
    config_template: test
   

  # roles:
  #   - ../roles/set_sot_variables
  #   - ../roles/apply_configuration_from_sot


  tasks:
    - debug: var=config_template
