---
- name: Configure network devices from SoT
  hosts: net01
  gather_facts: false

  # roles:
  #   - ../roles/set_sot_variables
  #   - ../roles/apply_configuration_from_sot

  tasks:
    - debug:
        msg:
          - "infra_path: {{ infra_path }}"
          - "inventory_hostname: {{ inventory_hostname }}"
          - "config_template: {{ config_template }}"

    # - debug: var=hostvars[inventory_hostname]
