---
- name: Configure network devices from SoT
  hosts: net01
  gather_facts: false

  # roles:
  #   - ../roles/set_sot_variables
  #   - ../roles/apply_configuration_from_sot

  tasks:
    - debug:
        msg:
          - "config_template1: {{ config_template }}"
