# Default action is to deploy network topology, use 'mode: destroy' to destroy topology
# Provide your topology file when running playbook via -e parameter or AAP Survey
---
- name: Manage network infrastructure with clab
  hosts: labhost
  become: true
  gather_facts: false

  roles:
    - role: ../roles/create_infrastructure
      vars:
        mode: deploy
        topology_file: ../topologies/net01/net01.clab.yml
