---
- name: Recover network interface
  hosts: "{{ device }}"

  tasks:
    - name: Shut down interface
      arista.eos.eos_config:
        lines:
          - shutdown
        parents: interface {{ interface }}

    - name: Pause for 5 seconds
      ansible.builtin.pause:
        seconds: 5

    - name: Enable interface
      arista.eos.eos_config:
        lines: no shutdown
        parents: interface {{ interface }}

    - name: Check interface status
      arista.eos.eos_command:
        commands:
          - command: show ip interface {{ interface }} brief
            output: json
      register: interface_status

    - name: Set variable with interface line protocol status
      ansible.builtin.set_fact:
         line_protocol_status: "{{ interface_status.stdout_lines[0].interfaces[interface].lineProtocolStatus }}"

    - name: Pass status in workflow
      ansible.builtin.set_stats:
        data:
          int_status_after_recovery:  line_protocol_status

    - name: Show interface status
      ansible.builtin.debug:
        var:  line_protocol_status
  
    - name: Verify if interface recovered
      ansible.builtin.assert:
        that:  line_protocol_status == "up"
        fail_msg: "Interface {{ interface }} recovery failed"
        success_msg: "Interface {{ interface }} recovered successfully"
