---
- name: Manage incident
  hosts: localhost
  vars:
    servicenow_instance:
      host: https://dev271481.service-now.com/
      username: admin
      password: yDpOvP5$Bn-2 # default password for temporary demo instance, encrypt or use environment variables if needed

  tasks:
    - name: Manage incident - interface recovery
      when: event_type == 'interface_status_change'
      block:
        - name: Create incident
          servicenow.itsm.incident:
            instance: "{{ servicenow_instance }}"
            state: new
            caller: ansible.eda
            short_description: Interface down
            description: Interface {{ interface }} on device {{ device }} is operationally down
            impact: low
            urgency: low
          register: new_incident
          tags: [create_incident, all]

        - name: Pass incident number in workflow
          ansible.builtin.set_stats:
            data:
              new_incident: new_incident

        - name: Update incident with recovery attempt
          servicenow.itsm.incident:
            instance: "{{ servicenow_instance }}"
            number: "{{ new_incident.record.number }}"
            state: in_progress
            other:
              work_notes: "Bounced interface {{ interface }} and verifying operational status"
          tags: [update_incident_succesfull, update_incident_unsuccesfull, all]

        - name: Update incident when recovery succesfull
          servicenow.itsm.incident:
            instance: "{{ servicenow_instance }}"
            number: "{{ new_incident.record.number }}"
            state: closed
            close_code: 'Solution provided'
            close_notes: "{{ 'Bouncing interface solved the issue, interface ' + interface + ' is up' }}"
          when: int_status_after_recovery == 'up'
          tags: [update_incident_succesfull, all]

        - name: Update incident when recovery unuccesfull
          servicenow.itsm.incident:
            instance: "{{ servicenow_instance }}"
            number: "{{ new_incident.record.number }}"
            state: in_progress
            other:
              work_notes: "{{ 'Bouncing interface did not solve the issue. Please troubleshoot problem manually' }} "
          when: int_status_after_recovery == 'down'
          tags: [update_incident_unsuccesfull, all]

    - name: Manage incident - enforce bgp network prefix configuration
      when: event_type == 'bgp_network_prefix_configuration_change'
      block:
        - name: Create incident
          servicenow.itsm.incident:
            instance: "{{ servicenow_instance }}"
            state: new
            caller: ansible.eda
            short_description: Bgp network prefix configuration on device {{ device }} changed
            description: Bgp network prefix configuration on device {{ device }} has been changed. Configuration will be reverted to the Source of Truth (SoT)
            impact: low
            urgency: low
          register: new_incident
          tags: [create_incident, all]

        - name: Update incident with resolution
          servicenow.itsm.incident:
            instance: "{{ servicenow_instance }}"
            number: "{{ new_incident.record.number }}"
            state: closed
            close_code: "Solution provided"
            close_notes: "BGP network prefix configuration reverted to SoT on device {{ device }}"
            other:
              work_notes: >
                BGP network prefix configuration on device {{ device }} has been
                successfully reverted to reflect the Source of Truth (SoT) configuration.
          tags: [update_incident_succesfull, all]
