---
- name: Manage incident
  hosts: localhost
  vars:
    host: https://dev271481.service-now.com/
    username: admin
    password: yDpOvP5$Bn-2 # default password for temporary demo instance, encrypt or use environment variables if needed

  tasks:
    - name: Manage incident - interface recovery
      when: event_type == 'interface_status_change'
      block:
        - name: Create incident
          servicenow.itsm.incident:
            instance:
              host: "{{ host }}"
              username: "{{ username }}"
              password: "{{ password }}"
            state: new
            caller: ansible.eda
            short_description: Interface down
            # description: Interface {{ interface }} on device {{ device }} is operationally down
            impact: low
            urgency: low
          register: new_incident
          tags: [create_incident, all]

        - name: Update the incident with resolution comments
          servicenow.itsm.incident:
            instance:
              host: "{{ host }}"
              username: "{{ username }}"
              password: "{{ password }}"
            number: "{{ new_incident.record.number }}"
            state: in_progress
            other:
              work_notes: "Bounced interface {{ interface }} and verifying if it still operationally down"
          tags: [update_incident, all]

        - name: Update the incident with comment when recovery failed
          servicenow.itsm.incident:
            instance:
              host: "{{ host }}"
              username: "{{ username }}"
              password: "{{ password }}"
            number: "{{ new_incident.record.number }}"
            state: in_progress
            other:
              work_notes: "Bouncing interface did not solve the issue. Please troubleshoot problem manually"
          when: lineProtocolStatus == 'down'
          tags: [update_incident, all]

        - name: Close the incident if resolved
          servicenow.itsm.incident:
            instance:
              host: "{{ host }}"
              username: "{{ username }}"
              password: "{{ password }}"
            number: "{{ new_incident.record.number }}"
            state: closed
            close_code: "Solution provided"
            close_notes: "Bouncing interface solved the issue, interface {{ interface }} is up"
          tags: [close_incident, all]

    # - name: Manage incident - enforce bgp network prefix configuration
    #   when: event_type == 'bgp_network_prefix_configuration_change'
    #   block:
    #     - name: Create incident
    #       servicenow.itsm.incident:
    #         instance:
    #           host: "{{ host }}"
    #           username: "{{ username }}"
    #           password: "{{ password }}"
    #         state: new
    #         caller: ansible.eda
    #         short_description: Bgp network prefix configuration changed
    #         description: Bgp network prefix configuration on device {{ device }} has been changed
    #         impact: low
    #         urgency: low
    #       register: new_incident
    #       tags: [create_incident, all]

    #     - name: Update the incident with resolution comments
    #       servicenow.itsm.incident:
    #         instance:
    #           host: "{{ host }}"
    #           username: "{{ username }}"
    #           password: "{{ password }}"
    #         number: "{{ new_incident.record.number }}"
    #         state: in_progress
    #         other:
    #           work_notes: "Bgp network prefix configuration on device {{ device }} has been reverted to reflect SoT configuration"
    #       tags: [update_incident, all]

    #     - name: Close the incident if resolved
    #       servicenow.itsm.incident:
    #         instance:
    #           host: "{{ host }}"
    #           username: "{{ username }}"
    #           password: "{{ password }}"
    #         number: "{{ new_incident.record.number }}"
    #         state: closed
    #         close_code: "Solution provided"
    #         close_notes: "Configuration reverted to SoT"
    #       tags: [close_incident, all]
